### ISSUE TITLE
Code tag strickthrough is misaligned

### ISSUE THREAD

**Issue by muan** [primer/primer-markdown#37]
https://github.com/github/github/pull/31324 (In Chrome)

![image](https://cloud.githubusercontent.com/assets/1153134/5797059/2fa52262-9fee-11e4-81f7-118100811696.png)

**Comment by fionnayao** [comment]
I did a quick experiment with using `vertical-align: text-top` on `h1`, `h3` and `p` elements. The strikethrough line does sit slightly higher. But in comparison to where the line is currently it's probably less noticeable? 

https://codepen.io/anon/pen/wKxOww
