### ISSUE TITLE
Headings w/o space are broken for now?

### ISSUE THREAD

**Issue by kiddick** [primer/primer-markdown#64]
Headings w/o space looks broken for now? Is there any reason for that?
Example:
##Heading (w/o space)

## Heading  (with space)

**Comment by shurcooL** [comment]
According to https://daringfireball.net/projects/markdown/syntax#header, there should be a space.

**Comment by kiddick** [comment]
But some times ago it was ok in both cases.

**Comment by shurcooL** [comment]
Yeah, it looks like the previous Markdown renderer handled headings without space incorrectly.

Since GitHub uses a new renderer now that follows the spec more accurately, the best thing to do probably is to update your markdown headings to have a space.

**Comment by broccolini** [comment]
Agree with @shurcooL - The spec requires that we use a space, I am not sure when we supported headings without a space but we're not likely to support that again since it's against the spec.
