### ISSUE TITLE
License agreement link in CONTRIBUTING.md is 404.

### ISSUE THREAD

**Issue by shurcooL** [primer/primer-markdown#67]
The second paragraph in [.github/CONTRIBUTING.md](https://github.com/primer/primer-markdown/blob/b739eac71a3b1ead20edde7de0a3575cf2cf60fb/.github/CONTRIBUTING.md) says:

> Before you do, would you mind reading [this license agreement](https://github.com/primer/primer-markdown/blob/master/.github/CLA.md)?

That link is 404.

Note that the link in CONTRIBUTING.md is relative and points to CLA.md file in [the same folder](https://github.com/primer/primer-markdown/tree/master/.github). That file doesn't exist there, hence the 404.

**Comment by broccolini** [comment]
I've opened an issue internally to get this update while we work on the new documentation site.
